# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_generator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14text_generator.proto\x12\rtextgenerator\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x0cTextResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t2Z\n\rTextGenerator\x12I\n\x0cGenerateText\x12\x1a.textgenerator.TextRequest\x1a\x1b.textgenerator.TextResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_generator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTREQUEST._serialized_start=39
  _TEXTREQUEST._serialized_end=66
  _TEXTRESPONSE._serialized_start=68
  _TEXTRESPONSE._serialized_end=106
  _TEXTGENERATOR._serialized_start=108
  _TEXTGENERATOR._serialized_end=198
# @@protoc_insertion_point(module_scope)
